package questions001to100.questions021to030;

import java.math.BigInteger;
import java.util.ArrayList;

public class Problem029 {
	/*
	 * Problem 29 - Distinct powers
	 * 
	 * Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:
	 * 
	 * If they are then placed in numerical order, with any repeats removed, we
	 * get the following sequence of 15 distinct terms:
	 * 
	 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
	 * 
	 * How many distinct terms are in the sequence generated by ab for 2 <= a <=
	 * 100 and 2 <= b <= 100?
	 */
	public static void main(String[] args) {
		long START = System.currentTimeMillis();
		
		ArrayList<BigInteger> vals = new ArrayList<BigInteger>();
		for (int i = 2; i <= 100; i++) {
			for (int j = 2; j <= 100; j++) {
				BigInteger pow = BigInteger.valueOf(i);
				pow = pow.pow(j);
				boolean contains = false;
				for (int k = 0; k < vals.size(); k++)
				{
					if (vals.get(k).compareTo(pow)==0)
						contains = true;
				}
				if (!contains)
				{
					vals.add(pow);
				}
			}
		}
		System.out.println(vals.size());

		long END = System.currentTimeMillis();
		System.out.println();
		if ((END - START) / 1000 > 2)
			System.out.println((END - START) / 1000 + " seconds");
		else
			System.out.println((END - START) + " ms");
	}
}
