package questions001to100.questions011to020;

public class Problem012 {
	/*
	 * Problem 12 - Highly divisible triangular number
	 * 
	 * The sequence of triangle numbers is generated by adding the natural
	 * numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
	 * 28. The first ten terms would be:
	 * 
	 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
	 * 
	 * Let us list the factors of the first seven triangle numbers:
	 * 
	 * 1: 1
	 * 3: 1,3 
	 * 6: 1,2,3,6
	 * 10: 1,2,5,10
	 * 15: 1,3,5,15
	 * 21: 1,3,7,21
	 * 28: 1,2,4,7,14,28 
	 * 
	 * We can see that 28 is the first triangle number to have
	 * over five divisors.
	 * 
	 * What is the value of the first triangle number to have over five hundred
	 * divisors?
	 */
	public static void main(String[] args) {
		long START = System.currentTimeMillis();

		long num = 0, count = 1;
		int dividibles = 0;
		while (dividibles < 250)
		{
			num+=count;
			count++;
			dividibles = 0;
			for (int i = 1; i <= Math.sqrt(num);i++)
				if (num%i==0)
					dividibles++;
		}
		System.out.println("Num - " + num);
		
		long END = System.currentTimeMillis();
		System.out.println();
		if ((END - START) / 1000 > 2)
			System.out.println((END - START) / 1000 + " seconds");
		else
			System.out.println((END - START) + " ms");
	}
}
